#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : microversion_parse
Version  : 1.0.0
Release  : 9
URL      : https://files.pythonhosted.org/packages/fc/43/f19cf3a0206d3f345640e6155f593066aa45f75327fc381848ac1d720224/microversion_parse-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/fc/43/f19cf3a0206d3f345640e6155f593066aa45f75327fc381848ac1d720224/microversion_parse-1.0.0.tar.gz
Summary  : OpenStack microversion header parser
Group    : Development/Tools
License  : Apache-2.0
Requires: microversion_parse-license = %{version}-%{release}
Requires: microversion_parse-python = %{version}-%{release}
Requires: microversion_parse-python3 = %{version}-%{release}
Requires: WebOb
BuildRequires : WebOb
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
microversion_parse
==================

A small set of functions to manage OpenStack `microversion`_ headers that can
be used in middleware, application handlers and decorators to effectively
manage microversions.

Also included, in the ``middleware`` module, is a ``MicroversionMiddleware``
that will process incoming microversion headers.

get_version
-----------

A simple parser for OpenStack microversion headers::

    import microversion_parse

    # headers is a dict of headers with folded (comma-separated
    # values) or a list of header, value tuples
    version = microversion_parse.get_version(
        headers, service_type='compute',
        legacy_headers=['x-openstack-nova-api-version'])

    # If headers are not already available, a dict of headers
    # can be extracted from the WSGI environ
    headers = microversion_parse.headers_from_wsgi_environ(environ)
    version = microversion_parse.get_version(
        headers, service_type='placement')

It processes microversion headers with the standard form::

    OpenStack-API-Version: compute 2.1

In that case, the response will be '2.1'.

If provided with a ``legacy_headers`` argument, this is treated as
a list of additional headers to check for microversions. Some examples of
headers include::

    OpenStack-telemetry-api-version: 2.1
    OpenStack-nova-api-version: 2.1
    X-OpenStack-nova-api-version: 2.1

If a version string cannot be found, ``None`` will be returned. If
the input is incorrect usual Python exceptions (ValueError,
TypeError) are allowed to raise to the caller.

parse_version_string
--------------------

A function to turn a version string into a ``Version``, a comparable
``namedtuple``::

    version_tuple = microversion_parse.parse_version_string('2.1')

If the provided string is not a valid microversion string, ``TypeError``
is raised.

extract_version
---------------

Combines ``get_version`` and ``parse_version_string`` to find and validate
a microversion for a given service type in a collection of headers::

    version_tuple = microversion_parse.extract_version(
        headers,  # a representation of headers, as accepted by get_version
        service_type,  # service type identify to match in headers
        versions_list,  # an ordered list of strings of version numbers that
                        # are the valid versions presented by this service
    )

``latest`` will be translated to whatever the max version is in versions_list.

If the found version is not in versions_list a ``ValueError`` is raised.

Note that ``extract_version`` does not support ``legacy_headers``.

MicroversionMiddleware
----------------------

A WSGI middleware that can wrap an application that needs to be microversion
aware. The application will get a WSGI environ with a
'SERVICE_TYPE.microversion' key that has a value of the microversion found at
an 'openstack-api-version' header that matches SERVICE_TYPE.  If no header is
found, the minimum microversion will be set. If the special keyword 'latest' is
used, the maximum microversion will be set.

If the requested microversion is not available a 406 response is returned.

If there is an error parsing a provided header, a 400 response is returned.

Otherwise the application is called.

The middleware is configured when it is created. Three parameters are required:

app
  The next WSGI middleware or application in the stack.

service_type
  The service type of the application, used to identify microversion headers.

versions_list
  An ordered list of legitimate microversions (as strings) for the application.
  It's assumed that any application that is using microversions will have such
  a list for its own housekeeping and documentation.

One named parameter is optional:

json_error_formatter
  A Webob error formatter that can be used to structure the response when JSON
  is expected.

For example::

    def app():
        app = middleware.MicroversionMiddleware(
            MyWSGIApp(), 'cats', ['1.0', '1.1', '1.2'])
        return app


.. _microversion: http://specs.openstack.org/openstack/api-wg/guidelines/microversion_specification.html

%package license
Summary: license components for the microversion_parse package.
Group: Default

%description license
license components for the microversion_parse package.


%package python
Summary: python components for the microversion_parse package.
Group: Default
Requires: microversion_parse-python3 = %{version}-%{release}

%description python
python components for the microversion_parse package.


%package python3
Summary: python3 components for the microversion_parse package.
Group: Default
Requires: python3-core
Provides: pypi(microversion-parse)

%description python3
python3 components for the microversion_parse package.


%prep
%setup -q -n microversion_parse-1.0.0
cd %{_builddir}/microversion_parse-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583173488
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/microversion_parse
cp %{_builddir}/microversion_parse-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/microversion_parse/92170cdc034b2ff819323ff670d3b7266c8bffcd
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/microversion_parse/92170cdc034b2ff819323ff670d3b7266c8bffcd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
